### ISSUE TITLE
Fetch account details authentication error

### ISSUE THREAD

**Issue by shivam-c20y** [twilio-labs/plugin-flex#9]
When i am trying to deploy using `twilio flex:plugins:deploy`, I am getting this error:
```
Error: Request get to https://api.twilio.com/2010-04-01/Accounts/ACXXXXXXXXXXXXXXX.json failed with status 401 and message Authenticate
    at Http.onError (/Users/XXXX/.twilio-cli/node_modules/flex-plugin-scripts/dist/clients/http.js:46:23)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
I have created a twilio-cli profile with my ACCOUNT_SID and AUTH_TOKEN and using the profile with the same ACCOUNT_SID as mentioned in the above URL.

**Comment by DylanMazurek** [comment]
I'm having the same issue, seems that "Standard API" credentials which the "twilio profile" creates do not have permission to that endpoint.
